<<<<<<< HEAD
# Generated by Django 3.1.4 on 2022-04-04 07:38

from django.db import migrations, models
=======
# Generated by Django 4.0.3 on 2022-04-04 07:40

from django.db import migrations, models
import tkinter.tix
>>>>>>> 10b63f8e25f663dd49d0d730ac5d1089d8250041


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('organization', models.CharField(max_length=20)),
=======
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=tkinter.tix.Tree, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tools', models.ManyToManyField(blank=True, null=True, to='core.tools')),
>>>>>>> 10b63f8e25f663dd49d0d730ac5d1089d8250041
            ],
        ),
    ]
