# Generated by Django 4.0.3 on 2022-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='core.tools'),
        ),
    ]
