# Generated by Django 3.1.4 on 2022-04-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220404_1358'),
        ('core', '0004_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
    ]
