# Generated by Django 4.0.3 on 2022-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_start_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
