# Generated by Django 4.0.3 on 2022-04-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_developer_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tools',
            new_name='tool',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='tool_name',
        ),
    ]
