# Generated by Django 3.1.4 on 2022-04-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20220404_1423'),
        ('core', '0006_rename_tools_tool_rename_name_customer_customer_name_and_more'),
    ]

    operations = [
    ]
