# Generated by Django 4.0.3 on 2022-04-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_car_alter_customer_id_alter_developer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='car',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
    ]
